name: Build Wheels

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.21.1

      - name: Build wheels
        env:
          CIBW_BUILD: cp310-manylinux* cp311-manylinux* cp312-manylinux*
        run: python -m cibuildwheel pkg/pypi --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: 'python-wheels'
          path: wheelhouse/*.whl
          if-no-files-found: error
