name: Build Wheels

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies from repository
        run: sudo apt-get install swig cmake

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install poetry
        run: python -m pip install poetry

      - name: Build wheels
        working-directory: ./pkg/pypi
        run: python -m poetry build

      - uses: actions/upload-artifact@v4
        with:
          name: 'python-wheels'
          path: pkg/pypi/dist/*.whl
          if-no-files-found: error
